
export const GET_ALL_PRODUCTS ="GET_ALL_PRODUCTS";
export const GET_PRODUCT_ID ="GET_PRODUCT_ID";
export const SINGLE_PRODUCT_DATA ="SINGLE_PRODUCT_DATA"
export const ADD_TO_CART = "ADD_TO_CART";
export const ADJUST_ITEM_QTY = "ADJUST_ITEM_QTY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";